---
title: "Initial Descriptives"
author: "Group 3: Institutional Characteristics"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: cayman
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Info.

Research Question:

### Dependent Variables

Info.

### Independent Variables

Info.

## Exploratory Questions

### Overall Trends

Guiding Questions:

- What is the percent of [institutions] that have seen an increase in undergraduate enrollment [in recent history]? What is the percent of [institutions] that have seen a decrease in undergraduate enrollment [in recent history]? 
- What percent of [institutions] have seen an increase in undergraduate enrollment [in recent history] of [scale, e.g., 10% or more]? What is the percent of [institutions] that have seen a decrease in undergraduate enrollment [in recent history] of [scale, e.g., 10% or more]? 

### Changing Enrollment

Guiding Questions:

- Is change in undergraduate enrollment [in recent history] correlated with change in application volume (number of applicants)? At what scale? [Same year] 
- Is change in undergraduate enrollment [in recent history] correlated with change in yield rate (% of admitted students who enroll at the institution)? At what scale? 
- Is change in undergraduate enrollment [in recent history] correlated with change in “attractor score” (number of applicants * yield rate)? At what scale? 
- Is change in undergraduate enrollment [in recent history] correlated with change in new student enrollment (first-time, first-year and transfer students, together and/or separately)? 

### Student Composition

Which student populations are increasing/decreasing in enrollment? 
- Enrollment by race/ethnicity 
- Percent Pell 
- Adult age (25-64) enrollment 

### Intersection between Enrollment and Graduation

TBD.

